title: Ditsypop
email: ditsypop@gmail.com
description: > 
  Personal site for @Ditsypop
baseurl: "" 
url: "https://ditsypop.tk" 
twitter_username: ditsypop
github_username:  ditsypop
markdown: kramdown
