title: Ditsypop
email: ditsypop@gmail.com
description: > 
  Personal site for @Ditsypop
baseurl: "" 
url: "http://ditsypop.github.io" 
twitter_username: ditsypop
github_username:  ditsypop
markdown: kramdown
